services:
  db:
    image: mysql:8.4
    container_name: ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  #app:
  #  build: ../  # if your Dockerfile is one level up
  #  container_name: ecommerce_app
  #  depends_on:
  #    - db
  #  environment:
  #    DB_HOST: db
  #    DB_PORT: 3306
  #    DB_USER: appuser
  #    DB_PASSWORD: apppass
  #    DB_NAME: ecommerce
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ../src/main/resources/logs:/app/logs
  #  restart: on-failure
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "10m"
  #      max-file: "5"

volumes:
  db_data:


#services:
#  mysql:
#    image: mysql:8.4
#    restart: always
#    container_name: ecommerce_mysql
#    environment:
#      MYSQL_DATABASE: ecommerce
#      MYSQL_USER: ecom_user
#      MYSQL_PASSWORD: password123
#      MYSQL_ROOT_PASSWORD: rootpass
#    ports:
#      - "3306:3306"
#    volumes:
#      - ../src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - mysql_data:/var/lib/mysql
